# -*- coding: utf-8 -*-
"""first pytorch program.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HimXzmfE0ll-zytVKzcW8XWdAEOh_Sz9
"""

#Import pytorch
import torch

#Creating 2 tensors
tensor1=torch.rand(3,3)
tensor2=torch.rand(3,3)

#Multiply the 2 tensor by using matmult function which refers to Matrix Multiplication
result=torch.matmul(tensor1,tensor2)

#Print tensor1, tensor2, Result
print(f"Tensor 1 is\n {tensor1}")
print(f"Tensor 2 is\n {tensor2}")
print(f"Result is\n {result}")

if torch.cuda.is_available():
  tersor1=tensor1.to("cuda")
  tensor2=tensor2.to("cuda")
  result=torch.matmul(tensor1,tensor2)
  print(f"Result is\n {result}")
else:
  print("CUDA is not available")